---
name: "Build Debian Packages"

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-deb-package:
    name: Build deb packages
    strategy:
      matrix:
        os:
         - ubuntu-22.04
         - ubuntu-20.04
         - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: Update package manager
        run: sudo apt-get update
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            libpam0g-dev \
            libudev-dev \
            libssl-dev \
            libsqlite3-dev \
            pkg-config \
            make
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'
      - name: "Doing the package build"
        run: |
          make -f platform/debian/Makefile debs/all
      - name: Upload debs
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-packages
          path: |
            target/*.deb
  upload-to-releases:
    name: Upload to releases
    needs: build-deb-package
    runs-on: ubuntu-latest
    steps:
      - name: Download previously built debs
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-packages
      - name: List packages
        run: |
          ls target
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Ubuntu Packages"
          files: target/*.deb
        if: ${{ github.ref == 'refs/heads/master' }}
